### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by trenkert** [marcowahl/org-section-numbers#1]
Hi, I've tested org-section-numbers and I find it really useful!

Could you provide it as a MELPA package?

**Comment by marcowahl** [comment]
hi!

thanks for your message!  cool that you like it.

i can try to ask the melpas if they accept the package but not before mid
August since i go on vacation.  now ;)

feel free to take over and ask the melpa guys for the add.


best regards,  marco

**Comment by marcowahl** [comment]
See https://github.com/melpa/melpa/pull/5067
